services:
  jetbot:
    # image: jetbot_main_docker
    image: jetbot_full_ros2
    # privileged: True
    cap_add:
     - SYS_NICE
    ulimits:
      rtprio: 99
      memlock: -1
    runtime: nvidia
    restart: always
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/home/app/ros2_ws/src
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    devices:
      - /dev/input:/dev/input
      - /dev/ttyLIDAR:/dev/ttyLIDAR
      - /dev/ttyMOTOR:/dev/ttyMOTOR
      - /dev/video0:/dev/video0
    working_dir: /home/app/ros2_ws
    # command: bash -c "source install/setup.bash && ros2 launch jetbot_bringup all_robot_launches.launch.py"
