/**/twist_mux:
  ros__parameters:
      topics:
        navigation:
          topic   : cmd_vel
          timeout : 0.5
          priority: 50
        joystick:
          topic   : cmd_vel_joy
          timeout : 0.5
          priority: 90
        robot_steering:
          topic   : cmd_vel_robot_steering
          timeout : 0.5
          priority: 100